#if !canImport(ObjectiveC)
import XCTest

extension TagRemoverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TagRemoverTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TagRemoverTests.__allTests__TagRemoverTests),
    ]
}
#endif
